Update lighthouse_testing.yml
Signed-off-by: Ruchi Sharma <ruchi492@gmail.com>

diff --git a/.github/workflows/lighthouse_testing.yml b/.github/workflows/lighthouse_testing.yml
--- a/.github/workflows/lighthouse_testing.yml
+++ b/.github/workflows/lighthouse_testing.yml
@@ -95,11 +95,14 @@ jobs:
             echo "[]" > .lighthouseci/assertion-results.json
           fi
 
+      - name: List contents of .lighthouseci
+        run: ls -R .lighthouseci || echo "Directory not found"
+
       - name: Upload Lighthouse Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: lighthouse-results
-          path: artifacts/
+          path: .lighthouseci/
 
       - name: Fail CI if Lighthouse assertion results indicate failures
         run: |
