ci metrics setup

diff --git a/.github/workflows/performance_testing.yml b/.github/workflows/performance_testing.yml
--- a/.github/workflows/performance_testing.yml
+++ b/.github/workflows/performance_testing.yml
@@ -1,9 +1,6 @@
-name: Performance Testing
+name: Lighthouse CI
 
 on:
-  push:
-    branches:
-      - main
   pull_request:
     branches:
       - main
@@ -18,19 +15,24 @@ jobs:
       - name: Install dependencies
         run: yarn install --frozen-lockfile
 
-      - name: Install Chrome
-        run: sudo apt-get install -y google-chrome-stable
-
       - name: Build OpenSearch Dashboards
         run: yarn build
 
       - name: Start OpenSearch Dashboards
-        run: yarn start & yarn wait-on http://localhost:5601
-
-      - name: Check Chrome Path
-        run: node -e "console.log(require('puppeteer').executablePath())"
+        run: yarn start --no-base-path & npx wait-on http://localhost:5601
 
       - name: Run Lighthouse CI
-        # env:
-        #   # LHCI_GITHUB_APP_TOKEN: ''
-        run: yarn lhci autorun
+        run: yarn lhci autorun || echo "Lighthouse assertion failed, check results"
+
+      - name: Post Lighthouse Report to PR
+        if: always()
+        run: |
+          echo "🚦 **Lighthouse CI Report**" > comment.txt
+          echo "" >> comment.txt
+          lhci upload --target=temporary-public-storage | tee lhci_output.txt
+          REPORT_URL=$(grep -o 'https://storage.googleapis.com/lighthouse-infrastructure-.*' lhci_output.txt | head -n 1)
+          echo "🔗 [View Full Lighthouse Report]($REPORT_URL)" >> comment.txt
+
+          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat comment.txt)"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
