add gthub token test
Signed-off-by: Ruchi Sharma <ruchi492@gmail.com>

diff --git a/.github/workflows/performance_testing.yml b/.github/workflows/performance_testing.yml
--- a/.github/workflows/performance_testing.yml
+++ b/.github/workflows/performance_testing.yml
@@ -83,7 +83,11 @@ jobs:
           curl 'http://localhost:5601/api/sample_data/ecommerce' -X 'POST' -H 'osd-version: 3.0.0' -H 'osd-xsrf: osd-fetch'
 
       - name: Run Lighthouse CI
-        run: LHCI_GITHUB_APP_TOKEN=${{ secrets.LHCI_GITHUB_APP_TOKEN }} yarn lhci autorun --verbose || echo "Lighthouse assertion failed, check results"
+        run: |
+          export LHCI_GITHUB_APP_TOKEN=${{ secrets.GITHUB_TOKEN }}
+          yarn lhci autorun --verbose || echo "Lighthouse assertion failed, check results"
+        env:
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Verify Lighthouse Results
         run: |
@@ -145,7 +149,7 @@ jobs:
           # Post comment on PR
           gh pr comment ${{ github.event.pull_request.number }} --body "$(cat comment.txt)"
         env:
-          LHCI_GITHUB_APP_TOKEN: ${{  secrets.LHCI_GITHUB_APP_TOKEN  }}
+          LHCI_GITHUB_APP_TOKEN: ${{  secrets.GITHUB_TOKEN  }}
 
       - name: Cleanup Lighthouse Reports
         run: rm -f .lhci_output.json .lighthouseci
